# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeBuild(DockerBaseRunner):
    """

    Usage:  docker compose build [OPTIONS] [SERVICE...]

    Build or rebuild services

    """

    build_arg: Optional[str] = None
    """Set build-time variables for services.
       --no-cache                Do not use cache when building the image
       --progress string         Set type of progress output (auto, tty,
       plain, quiet) (default "auto")
       --pull                    Always attempt to pull a newer version of
       the image.
       --push                    Push service images."""
    quiet: Optional[bool] = None
    """Don't print anything to STDOUT
       --ssh string              Set SSH authentications used when
       building service images. (use 'default'
       for using your default SSH Agent)"""
    _cmd: str = "build"
    _options: List[str] = [
        "quiet",
    ]
