# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeConfig(DockerBaseRunner):
    """

    Usage:  docker compose config [OPTIONS] [SERVICE...]

    Parse, resolve and render compose file in canonical format

    """

    no_consistency: Optional[bool] = None
    """Don't check model consistency - warning:"""
    output: Optional[str] = None
    """Save to file (default to stdout)"""
    quiet: Optional[bool] = None
    """Only validate the configuration, don't"""
    _cmd: str = "config"
    _options: List[str] = [
        "no_consistency",
        "quiet",
    ]
