# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeConfig(DockerBaseRunner):
    """

    Usage:  docker compose config [OPTIONS] [SERVICE...]

    Parse, resolve and render compose file in canonical format

    """

    format: Optional[str] = None
    """Format the output. Values: [yaml | json]
       (default "yaml")
       --hash string             Print the service config hash, one per line.
       --images                  Print the image names, one per line.
       --no-consistency          Don't check model consistency - warning:
       may produce invalid Compose output
       --no-interpolate          Don't interpolate environment variables.
       --no-normalize            Don't normalize compose model."""
    output: Optional[str] = None
    """Save to file (default to stdout)
       --profiles                Print the profile names, one per line."""
    quiet: Optional[bool] = None
    """Only validate the configuration, don't
       print anything.
       --resolve-image-digests   Pin image tags to digests.
       --services                Print the service names, one per line.
       --volumes                 Print the volume names, one per line."""
    _cmd: str = "config"
    _options: List[str] = [
        "quiet",
    ]
