# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeCreate(DockerBaseRunner):
    """

    Usage:  docker compose create [OPTIONS] [SERVICE...]

    Creates containers for a service.

    """

    force_recreate: Optional[bool] = None
    """Recreate containers even if their configuration"""
    no_recreate: Optional[bool] = None
    """If containers already exist, don't recreate"""
    pull: Optional[str] = None
    """Pull image before running"""
    remove_orphans: Optional[bool] = None
    """Remove containers for services not defined in"""
    _cmd: str = "create"
    _options: List[str] = [
        "force_recreate",
        "no_recreate",
        "remove_orphans",
    ]
