# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeCreate(DockerBaseRunner):
    """

    Usage:  docker compose create [OPTIONS] [SERVICE...]

    Creates containers for a service.

    """

    build: Optional[bool] = None
    """Build images before starting containers.
       --force-recreate   Recreate containers even if their configuration
       and image haven't changed.
       --no-build         Don't build an image, even if it's missing.
       --no-recreate      If containers already exist, don't recreate
       them. Incompatible with --force-recreate.
       --pull string      Pull image before running
       ("always"|"missing"|"never") (default "missing")
       --remove-orphans   Remove containers for services not defined in
       the Compose file.
       --scale scale      Scale SERVICE to NUM instances. Overrides the
       scale setting in the Compose file if present."""
    _cmd: str = "create"
    _options: List[str] = [
        "build",
    ]
