# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeEvents(DockerBaseRunner):
    """

    Usage:  docker compose events [OPTIONS] [SERVICE...]

    Receive real time events from containers.

    """

    json: Optional[bool] = None
    """Output events as a stream of json objects"""
    _cmd: str = "events"
    _options: List[str] = [
        "json",
    ]
