# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeExec(DockerBaseRunner):
    """

    Usage:  docker compose exec [OPTIONS] SERVICE COMMAND [ARGS...]

    Execute a command in a running container.

    """

    detach: Optional[bool] = None
    """Detached mode: Run command in the"""
    env: Optional[str] = None
    """Set environment variables"""
    index: Optional[int] = None
    """index of the container if there are"""
    workdir: Optional[str] = None
    """Path to workdir directory for this"""
    _cmd: str = "exec"
    _options: List[str] = [
        "detach",
    ]
