# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeLs(DockerBaseRunner):
    """

    Usage:  docker compose ls [OPTIONS]

    List running compose projects

    """

    all: Optional[bool] = None
    """Show all stopped Compose projects
       --filter filter   Filter output based on conditions provided.
       --format string   Format the output. Values: [table | json].
       (default "table")"""
    quiet: Optional[bool] = None
    """Only display IDs."""
    _cmd: str = "ls"
    _options: List[str] = [
        "all",
        "quiet",
    ]
