# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePs(DockerBaseRunner):
    """

    Usage:  docker compose ps [OPTIONS] [SERVICE...]

    List containers

    """

    all: Optional[bool] = None
    """Show all stopped containers (including those
       created by the run command)"""
    filter: Optional[str] = None
    """Filter services by a property (supported
       filters: status)."""
    format: Optional[str] = None
    """Format the output. Values: [table | json]
       (default "table")"""
    quiet: Optional[bool] = None
    """Only display IDs"""
    services: Optional[bool] = None
    """Display services"""
    status: Optional[str] = None
    """Filter services by status. Values: [paused |
       restarting | removing | running | dead |
       created | exited]"""
    _cmd: str = "ps"
    _options: List[str] = [
        "all",
        "quiet",
        "services",
    ]
