# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePull(DockerBaseRunner):
    """

    Usage:  docker compose pull [OPTIONS] [SERVICE...]

    Pull service images

    """

    ignore_pull_failures: Optional[bool] = None
    """Pull what it can and ignores images with"""
    _cmd: str = "pull"
    _options: List[str] = [
        "ignore_pull_failures",
    ]
