# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposePush(DockerBaseRunner):
    """

    Usage:  docker compose push [OPTIONS] [SERVICE...]

    Push service images

    """

    ignore_push_failures: Optional[bool] = None
    """Push what it can and ignores images with
       push failures
       --include-deps           Also push images of services declared as
       dependencies"""
    quiet: Optional[bool] = None
    """Push without printing progress information"""
    _cmd: str = "push"
    _options: List[str] = [
        "ignore_push_failures",
        "quiet",
    ]
