# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeStop(DockerBaseRunner):
    """

    Usage:  docker compose stop [OPTIONS] [SERVICE...]

    Stop services

    """

    timeout: Optional[int] = None
    """Specify a shutdown timeout in seconds (default 10)"""
    _cmd: str = "stop"
    _options: List[str] = []
