# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeUp(DockerBaseRunner):
    """

    Usage:  docker compose up [OPTIONS] [SERVICE...]

    Create and start containers

    """

    abort_on_container_exit: Optional[bool] = None
    """Stops all containers if any container"""
    detach: Optional[bool] = None
    """Detached mode: Run containers in the"""
    exit_code_from: Optional[str] = None
    """Return the exit code of the selected"""
    abort_on_container_exit: Optional[bool] = None
    """"""
    force_recreate: Optional[bool] = None
    """Recreate containers even if their"""
    no_recreate: Optional[bool] = None
    """If containers already exist, don't"""
    no_start: Optional[bool] = None
    """Don't start the services after creating"""
    pull: Optional[str] = None
    """Pull image before running"""
    remove_orphans: Optional[bool] = None
    """Remove containers for services not"""
    renew_anon_volumes: Optional[bool] = None
    """Recreate anonymous volumes instead of"""
    wait: Optional[bool] = None
    """Wait for services to be"""
    wait_timeout: Optional[int] = None
    """timeout waiting for application to be"""
    waitTimeout: Optional[int] = None
    """Use this waitTimeout in seconds for"""
    _cmd: str = "up"
    _options: List[str] = [
        "abort_on_container_exit",
        "detach",
        "abort_on_container_exit",
        "force_recreate",
        "no_recreate",
        "no_start",
        "remove_orphans",
        "renew_anon_volumes",
        "wait",
    ]
