# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeUp(DockerBaseRunner):
    """

    Usage:  docker compose up [OPTIONS] [SERVICE...]

    Create and start containers

    """

    abort_on_container_exit: Optional[bool] = None
    """Stops all containers if any container
       was stopped. Incompatible with -d
       --always-recreate-deps      Recreate dependent containers.
       Incompatible with --no-recreate.
       --attach stringArray        Attach to service output.
       --attach-dependencies       Attach to dependent containers.
       --build                     Build images before starting containers."""
    detach: Optional[bool] = None
    """Detached mode: Run containers in the
       background
       --exit-code-from string     Return the exit code of the selected
       service container. Implies
       --abort-on-container-exit
       --force-recreate            Recreate containers even if their
       configuration and image haven't changed.
       --no-attach stringArray     Don't attach to specified service.
       --no-build                  Don't build an image, even if it's missing.
       --no-color                  Produce monochrome output.
       --no-deps                   Don't start linked services.
       --no-log-prefix             Don't print prefix in logs.
       --no-recreate               If containers already exist, don't
       recreate them. Incompatible with
       --force-recreate.
       --no-start                  Don't start the services after creating
       them.
       --pull string               Pull image before running
       ("always"|"missing"|"never") (default
       "missing")
       --quiet-pull                Pull without printing progress information.
       --remove-orphans            Remove containers for services not
       defined in the Compose file."""
    renew_anon_volumes: Optional[bool] = None
    """Recreate anonymous volumes instead of
       retrieving data from the previous
       containers.
       --scale scale               Scale SERVICE to NUM instances.
       Overrides the scale setting in the
       Compose file if present.
       --timestamps                Show timestamps.
       --wait                      Wait for services to be
       running|healthy. Implies detached mode.
       --wait-timeout int          timeout waiting for application to be
       running|healthy."""
    waitTimeout: Optional[int] = None
    """Use this waitTimeout in seconds for
       container shutdown when attached or
       when containers are already running.
       (default 10)"""
    _cmd: str = "up"
    _options: List[str] = [
        "abort_on_container_exit",
        "detach",
        "renew_anon_volumes",
    ]
