# DO NOT EDIT: Autogenerated by /Users/jensen/kairos/docker-composer-v2/src/docker_composer_v2/_utils/generate_class.py
# for Docker Compose version v2.17.2

from typing import List, Optional

import attr

from docker_composer_v2.base import DockerBaseRunner


@attr.s(auto_attribs=True)
class DockerComposeVersion(DockerBaseRunner):
    """

    Usage:  docker compose version [OPTIONS]

    Show the Docker Compose version information

    """

    format: Optional[str] = None
    """Format the output. Values: [pretty | json].
       (Default: pretty)
       --short           Shows only Compose's version number."""
    _cmd: str = "version"
    _options: List[str] = []
